package librarymanagement;

public class Librarian {

    private String librarianName;

    // Constructor
    public Librarian(String librarianName) {
        this.librarianName = librarianName;
    }

    // Display librarian details
    public void displayLibrarian() {
        System.out.println("Librarian: " + librarianName);
    }

    // Approve book issue
    public boolean approveBookIssue(Book book) {

        if (book == null) {
            System.out.println("Book not found.");
            return false;
        }

        if (book.isAvailable()) {

            System.out.println("Issue approved by librarian.");

            return true;

        } else {

            System.out.println(
                    "Issue rejected. Book is already issued."
            );

            return false;
        }
    }

    // Collect fine
    public void collectFine(double fine) {

        if (fine > 0) {

            System.out.println(
                    "Fine collected successfully: ₹" + fine
            );

        } else {

            System.out.println("No fine to collect.");
        }
    }

    // Generate library report
    public void generateReport(Library library) {

        System.out.println(
                "Report generated by librarian: "
                        + librarianName
        );

        library.generateReport();
    }

    // Show due date reminder
    public void showDueDateReminder(Library library) {

        System.out.println(
                "Due date reminder checked by librarian: "
                        + librarianName
        );

        library.dueDateReminder();
    }
}